### ISSUE TITLE
Server serves up raw exception message as a response

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#2516]
**Describe the bug**

I deleted `templates/default.html`, which was in use by my web app, and Serverpod ended up serving up the raw exception message as a response: `Null check operator used on a null value`. A raw exception message like that should never be served as an HTTPS response!

This is the exception from the log:

```
INFO 2024-07-21T06:36:29.747372345Z [resource.labels.instanceId: serverpod-production-28gh] startup-script: ERROR: Null check operator used on a null value
INFO 2024-07-21T06:36:29.748434269Z [resource.labels.instanceId: serverpod-production-28gh] startup-script: #0 new Widget (package:serverpod/src/relic/web_widget.dart:34)
INFO 2024-07-21T06:36:29.748489428Z [resource.labels.instanceId: serverpod-production-28gh] startup-script: #1 new DefaultPageWidget (package:click_server/src/web/widgets/default_page_widget.dart:4)
INFO 2024-07-21T06:36:29.748510924Z [resource.labels.instanceId: serverpod-production-28gh] startup-script: #2 RouteRoot.build (package:click_server/src/web/routes/root.dart:9)
INFO 2024-07-21T06:36:29.748527268Z [resource.labels.instanceId: serverpod-production-28gh] startup-script: #3 WidgetRoute.handleCall (package:serverpod/src/relic/web_server.dart:301)
INFO 2024-07-21T06:36:29.748541658Z [resource.labels.instanceId: serverpod-production-28gh] startup-script: #4 WebServer._handleRouteCall (package:serverpod/src/relic/web_server.dart:172)
INFO 2024-07-21T06:36:29.748557188Z [resource.labels.instanceId: serverpod-production-28gh] startup-script: #5 WebServer._handleRequest (package:serverpod/src/relic/web_server.dart:153)
INFO 2024-07-21T06:36:29.748571805Z [resource.labels.instanceId: serverpod-production-28gh] startup-script: #6 WebServer._start (package:serverpod/src/relic/web_server.dart:94)
```

So there are two issues here: (1) that the `!` operator is being used dangerously; and (2) that the web server is directly delivering exception messages back to the browser. These should be logged, and something more generic reported to the user.

**Comment by lukehutch** [comment]
OK, I found the reason why `default.html` was being used -- I had followed the docs:

```dart
  pod.webServer.addRoute(RouteRoot(), '/');
  pod.webServer.addRoute(RouteRoot(), '/index.html');
```

I expected this to just serve the `index.html` as static content, but it intercepts that...

**Comment by lukehutch** [comment]
So I removed the `RouteRoot` handlers, but now `/` serves nothing. I need `/` to redirect to `index.html`... I'll try doing this as a redirect response, using the template system, but it would be nice if there could be a simple way to do this out of the box, for both static and dynamic content in `index.html`, since this is such a common need...

**Comment by lukehutch** [comment]
I tried this, but it didn't work...

```dart
  pod.webServer.addRoute(RouteRoot(), '/');
```

```dart
class RouteRoot extends WidgetRoute {
  @override
  Future<AbstractWidget> build(Session session, HttpRequest request) async =>
      WidgetRedirect(url: '/index.html');
}
```

**Comment by SandPod** [comment]
@lukehutch I want to clarify the issue here. It seems like the initial issue reported has been resolved.

The issues now is that you can't seem to server a static html file through relic?

**Comment by lukehutch** [comment]
Sorry, I need to go back and rework this, I was learning as I went...

The initial issue is partly resolved (once I realized why I was getting the error) -- but the parts that are not resolved are:

> `Null check operator used on a null value`

(this should never happen), and

> First off, a raw exception message like that should never be served as an HTTPS response...

The issue that is remaining is yes, I still can't figure out how to serve `index.html` at `/`. I tried a bunch of different things (e.g. the redirect I showed), and I keep getting a 404 or other error.

**Comment by lukehutch** [comment]
So to clarify on that last point: What I am currently doing is

```dart
  pod.webServer.addRoute(RouteRoot(), '/');
  pod.webServer.addRoute(RouteRoot(), '/index.html');
```

then I have

```
class RouteRoot extends WidgetRoute {
  @override
  Future<Widget> build(Session session, HttpRequest request) async =>
      Widget(name: 'index');
}
```

then I moved `index.html` into `web/templates`.

The page is correctly served from `https://<domain>/index.html`, but not from `https://<domain>/` . I get a 404 from the `/` path.

**Comment by lukehutch** [comment]
@SandPod I edited this issue to focus on the remaining two issues. I'll split out the 3rd problem into a separate issue.

**Comment by SandPod** [comment]
Awesome, thank you! 🙏

**Comment by lukehutch** [comment]
Yes, perfect. Thanks.
